package View;

import Controller.DesastreController;
import Controller.DonacionController;
import Controller.DonanteController;
import Model.Desastre;
import Model.Donacion;
import Model.DonacionInfo;
import Model.Donante;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;




public class PanelTabla extends javax.swing.JPanel {

    String dniInsertadoFiltrarDonante;
    
    public PanelTabla() {
        setLayout(new BorderLayout());
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnListar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFiltrar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnListar)
                .addGap(18, 18, 18)
                .addComponent(btnFiltrar)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABLA GENERAL DE DONACIONES");

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Donador", "Telefono", "Email", "Direccion", "DNI", "Desastre", "Fecha Desastre", "Ubicacion Desastre", "Donacion", "Cantidad Donacion", "Fecha Donacion"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void llamarLista() throws SQLException{
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();

        model.setRowCount(0);
        
        DonacionController controlDonacion = new DonacionController();
        
        List<DonacionInfo> donacionInfos = controlDonacion.listarDonacionesGeneral();

        for (DonacionInfo info : donacionInfos) {
            Object[] row = {
                info.getDonacion().getIdDonacion(),
                info.getDonante().getNombre(),
                info.getDonante().getTelefono(),
                info.getDonante().getEmail(),
                info.getDonante().getDireccion(),
                info.getDonante().getDni(),
                info.getDesastre().getNombreD(),
                info.getDesastre().getFecha(),
                info.getDesastre().getUbicacion(),
                info.getDonacion().getTipo(),
                info.getDonacion().getCantidad(),
                info.getDonacion().getFecha()
            };
            model.addRow(row);
        }
    }
    private void llamarListaFiltrada()throws SQLException{
        DefaultTableModel model = (DefaultTableModel) Table1.getModel();

        model.setRowCount(0);
        
        DonacionController controlDonacion = new DonacionController();
        
        List<DonacionInfo> donacionInfos = controlDonacion.listarDonacionesFiltradas(dniInsertadoFiltrarDonante);

        for (DonacionInfo info : donacionInfos) {
            Object[] row = {
                info.getDonacion().getIdDonacion(),
                info.getDonante().getNombre(),
                info.getDonante().getTelefono(),
                info.getDonante().getEmail(),
                info.getDonante().getDireccion(),
                info.getDonante().getDni(),
                info.getDesastre().getNombreD(),
                info.getDesastre().getFecha(),
                info.getDesastre().getUbicacion(),
                info.getDonacion().getTipo(),
                info.getDonacion().getCantidad(),
                info.getDonacion().getFecha()
            };
            model.addRow(row);
        }
    }
    
    

    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try {
            llamarLista();
        } catch (SQLException ex) {
            Logger.getLogger(PanelTabla.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
         dniInsertadoFiltrarDonante = JOptionPane.showInputDialog(null, "Por favor, ingresa el DNI del Donante:");
        
        if (dniInsertadoFiltrarDonante != null && !dniInsertadoFiltrarDonante.trim().isEmpty()) {
             
             try {
                 llamarListaFiltrada();
             } catch (SQLException ex) {
                 Logger.getLogger(PanelTabla.class.getName()).log(Level.SEVERE, null, ex);
             }
             
             
         }else{
             JOptionPane.showMessageDialog(this, "Se cancelo la operacion de modificar");
         }
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
